name: Run Script

on: [issues, issue_comment]

jobs:
  build:
    uses: alpico/workflows/.github/workflows/notion_bridge.yml@main
    with:
      page: "863bce68f5034391bc7d34f6495fe426"
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      notion_api_key: ${{ secrets.NOTION_API_KEY }}
